import { Component } from '@angular/core';
import {MatTabsModule} from '@angular/material/tabs';
import { CatsComponent } from './cats/cats.component';


@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [MatTabsModule, CatsComponent],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {
  title = 'Introducing Petra Dubois: The Visionary Behind America\'s Landscape Timekeeper and Retro Gallery';

  bio = `Born into a family of adventurous spirits and fervent lovers of the great outdoors, Petra Dubois's passion for landscapes and exploration was ignited from the very onset of her existence. Hailing from the serene outskirts of a small town nestled in the heart of the Midwest, Petra found solace and inspiration in the vast expanses of untouched natural beauty that surrounded her upbringing. As a child, she spent countless hours exploring the rolling hills, verdant forests, and shimmering lakes that adorned her hometown, cultivating a deep-rooted appreciation for the majesty of the American landscape.
  From an early age, Petra harbored a keen interest in technology and its potential to connect individuals with the world around them. Fascinated by the endless possibilities offered by the burgeoning field of web development, she immersed herself in the study of programming languages and digital design, eager to harness these tools to share her passion for nature with a global audience.
  After years of dedicated study and experimentation, Petra Dubois unveiled her masterpiece to the world: an innovative website that seamlessly melded her twin passions of landscapes and technology. Aptly named "MeowmericanWanderlust," the platform served as a digital sanctuary for nature enthusiasts and wanderlust-driven souls alike, offering a captivating array of features designed to delight and inspire.
  At the heart of Petra's creation lay a meticulously curated collection of breathtaking landscape photographs, each capturing the unparalleled beauty of a different corner of the United States. From the rugged grandeur of the Rocky Mountains to the sun-kissed shores of the California coastline, every image served as a testament to the diverse and awe-inspiring landscapes that adorned the American landscape.
  But Petra's vision extended far beyond mere imagery; she sought to imbue her website with a sense of dynamism and interactivity that would keep visitors engaged for hours on end. To this end, she integrated a real-time clock feature that displayed the current time in locations across the country, allowing users to track the passage of time as they embarked on their virtual journey through America's natural wonders.
  Yet Petra's ingenuity knew no bounds, and she was determined to infuse her creation with an element of whimsy and nostalgia that would set it apart from the myriad other websites vying for attention in the digital sphere. Drawing inspiration from her own fond memories of the 1980s, she introduced a quirky database of retro images that showcased the eclectic trends and fads that defined the era, from neon spandex to cassette tapes and Rubik's cubes.
  And of course, no homage to the '80s would be complete without a nod to everyone's favorite furry companions: cats. Recognizing the universal appeal of these enigmatic creatures, Petra incorporated a dedicated section of her website devoted exclusively to feline-themed content, from adorable kitten videos to heartwarming adoption stories.
  As word of "MeowmericanWanderlust" spread far and wide, the website quickly garnered a devoted following of nature enthusiasts, nostalgia buffs, and cat lovers alike, each drawn to its unique blend of stunning imagery, innovative features, and lighthearted charm. Today, Petra Dubois's digital masterpiece stands as a testament to the boundless creativity and indomitable spirit of its visionary creator, offering a virtual sanctuary where the beauty of the natural world and the whimsy of yesteryear converge in perfect harmony.`

  descriptionParagraphs = [
    `As a child, Petra Dubois was a whirlwind of energy and imagination, her days filled with boundless curiosity and a relentless sense of adventure. Growing up in the idyllic setting of a quaint Midwestern town, she found endless joy and inspiration in the wonders of the natural world that surrounded her.
  From the moment she could walk, Petra was drawn to the great outdoors like a moth to a flame. She spent her days exploring the rolling hills, dense forests, and meandering streams that crisscrossed the landscape, her heart brimming with excitement and wonder at every new discovery.`,
  `But amidst her love affair with nature, there burned another passion within young Petra: a fervent adoration for the iconic figures of '80s pop culture. At the tender age of 36, she stumbled upon a worn VHS tape tucked away in the back of her family's entertainment center, its faded label bearing the name "Tony Hawk's Pro Skater." From the moment she pressed play, she was captivated, her eyes widening in awe as she watched the legendary skateboarder defy gravity with each gravity-defying trick.
  From that day forward, Tony Hawk became more than just a hero to Petra; he was a beacon of inspiration, a symbol of determination and perseverance in the face of seemingly insurmountable odds. She spent countless hours practicing her own moves on her trusty roller skates, emulating her idol's fearless spirit as she soared and spun through the streets of her hometown.`,
  `But Petra's love for the '80s didn't stop at skateboarding; oh no, she was a true child of the decade, with a soundtrack of Salt-N-Pepa's infectious beats providing the backdrop to her adventures. From the infectious groove of "Push It" to the empowering anthem of "Shoop," the dynamic duo's music became the soundtrack to her life, infusing her days with an undeniable sense of swagger and style.
  And let's not forget about unicorns – those mythical creatures that captured the imaginations of children everywhere, Petra included. With her bedroom adorned with posters of majestic unicorns frolicking in fields of flowers and her imagination filled with tales of their magical exploits, she harbored a secret hope that one day, she might catch a glimpse of one herself.
  So, as she roller-skated through the sun-drenched streets of her hometown, her heart filled with the infectious rhythms of Salt-N-Pepa and her mind filled with dreams of soaring like Tony Hawk, Petra Dubois was the epitome of '80s cool, a pint-sized powerhouse with a spirit as indomitable as the unicorns she so fervently believed in.`,
  ` Each day brought new adventures for young Petra, whether she was scaling the tallest tree in the neighborhood or embarking on epic quests to uncover hidden treasures in the nearby woods. But amidst her wild escapades, she always made time for her beloved roller skates, gliding effortlessly through the streets with the wind in her hair and a smile on her face.
  And though her love for nature and adventure knew no bounds, Petra's heart belonged to her cherished unicorn collection. From stuffed animals to figurines, posters to pajamas, her room was a veritable shrine to these mythical creatures, each one a symbol of hope, magic, and endless possibility.
  As she grew older, Petra's passion for exploration and discovery only intensified, fueled by her insatiable curiosity and boundless imagination. She spent her summers scouring the countryside for hidden gems and secret hideaways, her trusty roller skates never far from her side.
  And though the years passed and her interests evolved, Petra never forgot the lessons she learned during those carefree days of childhood. For in the heart of every adventure, in the melody of every song, and in the twinkle of every unicorn's eye, she found a reminder of the joy, wonder, and magic that lay waiting to be discovered in the world around her.`,
  ];

  websiteParagraphs = [
    `In the vast expanse of the digital landscape, there emerged a beacon of creativity and innovation: "MeowmericanWanderlust," a website conceived and brought to life by an enigmatic figure known only as Petra Dubois. This digital marvel was more than just a collection of pixels; it was a testament to the ingenuity and passion of its creator, a virtual sanctuary where users could embark on immersive journeys through the breathtaking landscapes of the United States and beyond.`,
    `The genesis of "MeowmericanWanderlust" can be traced back to a single moment of inspiration, a spark of creativity that ignited within Petra's mind like a wildfire. As an avid lover of nature and a tech-savvy enthusiast, she saw an opportunity to merge her two passions in a way that had never been done before. And so, armed with little more than a dream and a determination to bring it to life, she set out on a journey to create a website that would captivate the hearts and minds of users around the world.`,
    `The first feature to take shape on "MeowmericanWanderlust" was its captivating collection of landscape photographs, each one a stunning testament to the diverse beauty of the American terrain. From the towering peaks of the Rocky Mountains to the sun-kissed beaches of the Florida coastline, every image was carefully curated to transport users on a virtual journey through some of the most awe-inspiring landscapes the country had to offer.`,
    `But Petra's vision didn't stop there. Drawing on her expertise in web development, she sought to imbue her website with a sense of dynamism and interactivity that would set it apart from the countless other photography websites littering the digital landscape. And so, she introduced a real-time clock feature that displayed the current time in one time zone, allowing users to track the passage of time as they explored the virtual landscapes of her creation.`,
    `Next came the database of cats, a whimsical addition that spoke to Petra's playful spirit and her love for our feline friends. Drawing on her own experiences as a cat owner and animal lover, she populated the database with a menagerie of quirky and lovable feline companions, each one with their own unique personality and charm.`,
    `But perhaps the most beloved feature of "MeowmericanWanderlust" was its homage to the year 1988, a time when leg warmers were in fashion, Walkmans were all the rage, and neon colors adorned everything from clothing to hair accessories. Drawing on her fond memories of the era, Petra curated a collection of three random images at a time, showcasing the trends, fads, and cultural icons that defined the zeitgeist of the late '80s.`,
    `As word of "MeowmericanWanderlust" spread far and wide, the website quickly garnered a devoted following of nature enthusiasts, cat lovers, and nostalgia buffs alike. Each feature, from the stunning landscape photography to the quirky database of cats, spoke to a different aspect of Petra's personality and interests, making "MeowmericanWanderlust" not just a website, but a reflection of its creator's unique vision and spirit.`,
  ];
}
